// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.
DEFINE
  MEASURE 'mlb_player_batting_boxscores'[AVG] = DIVIDE([H], [AB], 0)
EVALUATE
  ROW(
    "Measure Created", "AVG batting average measure defined successfully"
  )