createOrReplace

	table mlb_boxscores_2025-07-05
		lineageTag: 8b80e307-77cd-4bd6-8649-7d4b173456a1

		measure 'Hits (H)' =
				
				SUM('mlb_boxscores_2025-07-05'[hits])
			formatString: 0
			lineageTag: 78dc68c5-6499-4871-b69d-72bb0afb4e43

			extendedProperty MeasureTemplate = {"version":0,"daxTemplateName":"MathematicalAddition"}

			changedProperty = FormatString
            
        measure 'Sum Batting Order' =
                SUM('mlb_boxscores_2025-07-05'[batting_order])
            formatString: 0

        measure 'Sum Games Played' =
                SUM('mlb_boxscores_2025-07-05'[gamesPlayed])
            formatString: 0

        measure 'Sum Flyouts' =
                SUM('mlb_boxscores_2025-07-05'[flyouts])
            formatString: 0

        measure 'Sum Ground Outs' =
                SUM('mlb_boxscores_2025-07-05'[groundOuts])
            formatString: 0

        measure 'Sum Airouts' =
                SUM('mlb_boxscores_2025-07-05'[airouts])
            formatString: 0

        measure 'Sum Runs' =
                SUM('mlb_boxscores_2025-07-05'[runs])
            formatString: 0

        measure 'Sum Doubles' =
                SUM('mlb_boxscores_2025-07-05'[doubles])
            formatString: 0

        measure 'Sum Triples' =
                SUM('mlb_boxscores_2025-07-05'[triples])
            formatString: 0

        measure 'Sum Home Runs' =
                SUM('mlb_boxscores_2025-07-05'[homeRuns])
            formatString: 0

        measure 'Sum Strike Outs' =
                SUM('mlb_boxscores_2025-07-05'[strikeOuts])
            formatString: 0

        measure 'Sum Base On Balls' =
                SUM('mlb_boxscores_2025-07-05'[baseOnBalls])
            formatString: 0

        measure 'Sum Intentional Walks' =
                SUM('mlb_boxscores_2025-07-05'[intentionalWalks])
            formatString: 0

        measure 'Sum Hits' =
                SUM('mlb_boxscores_2025-07-05'[hits])
            formatString: 0

        measure 'Sum Hit By Pitch' =
                SUM('mlb_boxscores_2025-07-05'[hitByPitch])
            formatString: 0

        measure 'Sum At Bats' =
                SUM('mlb_boxscores_2025-07-05'[atBats])
            formatString: 0

        measure 'Sum Caught Stealing' =
                SUM('mlb_boxscores_2025-07-05'[caughtStealing])
            formatString: 0

        measure 'Sum Stolen Bases' =
                SUM('mlb_boxscores_2025-07-05'[stolenBases])
            formatString: 0

        measure 'Sum Plate Appearances' =
                SUM('mlb_boxscores_2025-07-05'[plateAppearances])
            formatString: 0

        measure 'Sum Left On Base' =
                SUM('mlb_boxscores_2025-07-05'[leftOnBase])
            formatString: 0

        measure 'Sum Total Bases' =
                SUM('mlb_boxscores_2025-07-05'[totalBases])
            formatString: 0

        measure 'Sum RBI' =
                SUM('mlb_boxscores_2025-07-05'[rbi])
            formatString: 0

		column team
			dataType: int64
			formatString: 0
			lineageTag: 7ef40891-8e82-45cf-bf91-3c96817cce2d
			summarizeBy: sum
			sourceColumn: team

			annotation SummarizationSetBy = Automatic

		column player_id
			dataType: int64
			formatString: 0
			lineageTag: 7a1dde77-cd90-4b34-b1a7-05ff4d9cc699
			summarizeBy: none
			sourceColumn: player_id

			annotation SummarizationSetBy = Automatic

		column batting_order
			dataType: int64
			formatString: 0
			lineageTag: 0fa7727b-e5f5-4c27-9fe4-f26d7e4f9140
			summarizeBy: none
			sourceColumn: batting_order

			annotation SummarizationSetBy = User

		column summary
			dataType: string
			lineageTag: 09394b66-6956-4010-addb-3b88e184e2c8
			summarizeBy: none
			sourceColumn: summary

			annotation SummarizationSetBy = Automatic

		column gamesPlayed
			dataType: int64
			formatString: 0
			lineageTag: b325907e-d380-4989-be31-c3e001f93479
			summarizeBy: none
			sourceColumn: gamesPlayed

			annotation SummarizationSetBy = User

		column flyouts
			dataType: int64
			formatString: 0
			lineageTag: 0e0c5c66-b406-4a3f-9660-38594f12b5e2
			summarizeBy: none
			sourceColumn: flyouts

			annotation SummarizationSetBy = User

		column groundOuts
			dataType: int64
			formatString: 0
			lineageTag: 3e9f4f38-7e66-464b-b8d6-febf52c1d279
			summarizeBy: sum
			sourceColumn: groundOuts

			annotation SummarizationSetBy = Automatic

		column airouts
			dataType: int64
			formatString: 0
			lineageTag: 684daee4-5dd3-45f7-907f-e8b55c823fbe
			summarizeBy: none
			sourceColumn: airouts

			annotation SummarizationSetBy = User

		column runs
			dataType: int64
			formatString: 0
			lineageTag: 722047a2-2262-453c-b863-68965fae76e5
			summarizeBy: sum
			sourceColumn: runs

			annotation SummarizationSetBy = Automatic

		column doubles
			dataType: int64
			formatString: 0
			lineageTag: 9920369f-d6a7-446b-99ec-2ab9b075a4fb
			summarizeBy: none
			sourceColumn: doubles

			annotation SummarizationSetBy = User

		column triples
			dataType: int64
			formatString: 0
			lineageTag: 88a4d04b-62a5-426f-a651-04f98665303a
			summarizeBy: sum
			sourceColumn: triples

			annotation SummarizationSetBy = Automatic

		column homeRuns
			dataType: int64
			formatString: 0
			lineageTag: 8bf588d8-d15c-409d-93ca-c6db14cfa158
			summarizeBy: sum
			sourceColumn: homeRuns

			annotation SummarizationSetBy = Automatic

		column strikeOuts
			dataType: int64
			formatString: 0
			lineageTag: fcad1837-5a86-46fd-8e91-bf8ccfabdd31
			summarizeBy: sum
			sourceColumn: strikeOuts

			annotation SummarizationSetBy = Automatic

		column baseOnBalls
			dataType: int64
			formatString: 0
			lineageTag: 4081b6d6-2be8-4835-8c98-294486eae512
			summarizeBy: none
			sourceColumn: baseOnBalls

			annotation SummarizationSetBy = User

		column intentionalWalks
			dataType: int64
			formatString: 0
			lineageTag: a9bc6df2-3cbf-48a1-bf7e-c10efede8f45
			summarizeBy: sum
			sourceColumn: intentionalWalks

			annotation SummarizationSetBy = Automatic

		column hits
			dataType: int64
			formatString: 0
			lineageTag: b6d2163f-209d-4c3b-a173-25d4560e2cb8
			summarizeBy: sum
			sourceColumn: hits

			annotation SummarizationSetBy = Automatic

		column hitByPitch
			dataType: int64
			formatString: 0
			lineageTag: a360f7dd-6d42-4c43-85ed-bdd226fc03b6
			summarizeBy: sum
			sourceColumn: hitByPitch

			annotation SummarizationSetBy = Automatic

		column atBats
			dataType: int64
			formatString: 0
			lineageTag: 028b8bfe-475a-41c4-8b5b-3f3253da188c
			summarizeBy: none
			sourceColumn: atBats

			annotation SummarizationSetBy = User

		column caughtStealing
			dataType: int64
			formatString: 0
			lineageTag: 22dd18d1-5fa9-408f-b61d-f5c406777362
			summarizeBy: none
			sourceColumn: caughtStealing

			annotation SummarizationSetBy = User

		column stolenBases
			dataType: int64
			formatString: 0
			lineageTag: 6ab12620-6462-4852-b9d8-5ae13d76e36f
			summarizeBy: sum
			sourceColumn: stolenBases

			annotation SummarizationSetBy = Automatic

		column groungdIntoDoublePlay
			dataType: string
			lineageTag: ab239572-1d43-43cd-93bd-1951c21c482e
			summarizeBy: none
			sourceColumn: groungdIntoDoublePlay

			annotation SummarizationSetBy = Automatic

		column groundedIntoTriplePlay
			dataType: string
			lineageTag: 86e17ece-654f-4552-8bfb-6eef652c70eb
			summarizeBy: none
			sourceColumn: groundedIntoTriplePlay

			annotation SummarizationSetBy = Automatic

		column plateAppearances
			dataType: int64
			formatString: 0
			lineageTag: effdcf47-7f25-4970-ad72-63d85c3787b0
			summarizeBy: sum
			sourceColumn: plateAppearances

			annotation SummarizationSetBy = Automatic

		column leftOnBase
			dataType: int64
			formatString: 0
			lineageTag: 9e79f1f2-986b-48e8-9eda-c2e1128fca47
			summarizeBy: sum
			sourceColumn: leftOnBase

			annotation SummarizationSetBy = Automatic

		column totalBases
			dataType: int64
			formatString: 0
			lineageTag: def7b6e6-3b64-4a43-9438-ca8be744841c
			summarizeBy: sum
			sourceColumn: totalBases

			annotation SummarizationSetBy = Automatic

		column rbi
			dataType: int64
			formatString: 0
			lineageTag: f3720cac-4edf-4875-ba12-d39b240693af
			summarizeBy: sum
			sourceColumn: rbi

			annotation SummarizationSetBy = Automatic

		partition mlb_boxscores_2025-07-05 = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents("C:\Users\metsy\source\repos\mlb-data\assets\csv\boxscores\mlb_boxscores_2025-07-05.csv"),[Delimiter=",", Columns=26, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team", Int64.Type}, {"player_id", Int64.Type}, {"batting_order", Int64.Type}, {"summary", type text}, {"gamesPlayed", Int64.Type}, {"flyouts", Int64.Type}, {"groundOuts", Int64.Type}, {"airouts", Int64.Type}, {"runs", Int64.Type}, {"doubles", Int64.Type}, {"triples", Int64.Type}, {"homeRuns", Int64.Type}, {"strikeOuts", Int64.Type}, {"baseOnBalls", Int64.Type}, {"intentionalWalks", Int64.Type}, {"hits", Int64.Type}, {"hitByPitch", Int64.Type}, {"atBats", Int64.Type}, {"caughtStealing", Int64.Type}, {"stolenBases", Int64.Type}, {"groungdIntoDoublePlay", type text}, {"groundedIntoTriplePlay", type text}, {"plateAppearances", Int64.Type}, {"leftOnBase", Int64.Type}, {"totalBases", Int64.Type}, {"rbi", Int64.Type}})
					in
					    #"Changed Type"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table

