table player_info
	lineageTag: 5a117058-adfd-46c0-a4db-e3b17ec6446e

	column id
		dataType: string
		lineageTag: a5ad8c57-9d7c-418f-9689-6156582ddfc2
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column fullName
		dataType: string
		lineageTag: 8045c2bc-6a21-48c6-ba20-4a33f8e41e86
		summarizeBy: none
		sourceColumn: fullName

		annotation SummarizationSetBy = Automatic

	column link
		dataType: string
		lineageTag: 62f28dca-2d5a-4024-b084-b9cec8fcd38b
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column firstName
		dataType: string
		lineageTag: 2bf6d4ae-e701-4820-a948-0446e95c089e
		summarizeBy: none
		sourceColumn: firstName

		annotation SummarizationSetBy = Automatic

	column lastName
		dataType: string
		lineageTag: beaecd47-fa37-4a4a-8229-1a419d357ff4
		summarizeBy: none
		sourceColumn: lastName

		annotation SummarizationSetBy = Automatic

	column primaryNumber
		dataType: string
		lineageTag: 45a9e54b-74bb-4802-94d4-4b4cb6d319df
		summarizeBy: none
		sourceColumn: primaryNumber

		annotation SummarizationSetBy = Automatic

	column birthDate
		dataType: string
		lineageTag: 719dce63-cf13-4090-853d-498fd47c8ab1
		summarizeBy: none
		sourceColumn: birthDate

		annotation SummarizationSetBy = Automatic

	column currentAge
		dataType: string
		lineageTag: f3dcecd5-1473-4581-b3d8-4b099fc8dde0
		summarizeBy: none
		sourceColumn: currentAge

		annotation SummarizationSetBy = Automatic

	column birthCity
		dataType: string
		lineageTag: d6db8784-ee0c-4d77-9d68-7496f812338d
		summarizeBy: none
		sourceColumn: birthCity

		annotation SummarizationSetBy = Automatic

	column birthCountry
		dataType: string
		lineageTag: a90a7696-bc90-402f-9859-61b2114e5930
		summarizeBy: none
		sourceColumn: birthCountry

		annotation SummarizationSetBy = Automatic

	column height
		dataType: string
		lineageTag: a0e88e39-d9cc-407b-b44c-25e0d6f596da
		summarizeBy: none
		sourceColumn: height

		annotation SummarizationSetBy = Automatic

	column weight
		dataType: string
		lineageTag: 6f2a407c-d029-4473-92cf-3c4b28983094
		summarizeBy: none
		sourceColumn: weight

		annotation SummarizationSetBy = Automatic

	column active
		dataType: string
		lineageTag: 74932189-5220-4116-a565-32ba63c1420e
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column useName
		dataType: string
		lineageTag: e09a03ec-d605-49de-bbca-9d8b2118d448
		summarizeBy: none
		sourceColumn: useName

		annotation SummarizationSetBy = Automatic

	column useLastName
		dataType: string
		lineageTag: 02173084-c87c-45df-ba03-bcffda854eda
		summarizeBy: none
		sourceColumn: useLastName

		annotation SummarizationSetBy = Automatic

	column middleName
		dataType: string
		lineageTag: 6a72f44b-bcd9-4f73-8faa-07f94e862177
		summarizeBy: none
		sourceColumn: middleName

		annotation SummarizationSetBy = Automatic

	column boxscoreName
		dataType: string
		lineageTag: ebde51a6-a8d8-49df-a56b-0d273941143a
		summarizeBy: none
		sourceColumn: boxscoreName

		annotation SummarizationSetBy = Automatic

	column nickName
		dataType: string
		lineageTag: 93302b89-8a62-42a0-af9a-52dd7ea06df0
		summarizeBy: none
		sourceColumn: nickName

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 68b4b15b-d001-4457-9570-77e9ca6151cf
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column isPlayer
		dataType: string
		lineageTag: 0781627f-89de-4c5b-88fa-54fec1398c10
		summarizeBy: none
		sourceColumn: isPlayer

		annotation SummarizationSetBy = Automatic

	column isVerified
		dataType: string
		lineageTag: 985a8cf9-58ee-48cb-801a-2e5134e248d6
		summarizeBy: none
		sourceColumn: isVerified

		annotation SummarizationSetBy = Automatic

	column pronunciation
		dataType: string
		lineageTag: 71ae1b34-8221-4826-85a5-679e74417be5
		summarizeBy: none
		sourceColumn: pronunciation

		annotation SummarizationSetBy = Automatic

	column mlbDebutDate
		dataType: string
		lineageTag: 4b95b37a-e51a-44cb-96a2-1f7b14a4e8e6
		summarizeBy: none
		sourceColumn: mlbDebutDate

		annotation SummarizationSetBy = Automatic

	column nameFirstLast
		dataType: string
		lineageTag: 735778fc-945e-4591-ab9a-ed3e5c5f4dd1
		summarizeBy: none
		sourceColumn: nameFirstLast

		annotation SummarizationSetBy = Automatic

	column nameSlug
		dataType: string
		lineageTag: dd018cae-82b9-49d6-8016-0ef8f7f8ff74
		summarizeBy: none
		sourceColumn: nameSlug

		annotation SummarizationSetBy = Automatic

	column firstLastName
		dataType: string
		lineageTag: 00e40dca-d6ce-45fe-8cb2-3c12c55b34b0
		summarizeBy: none
		sourceColumn: firstLastName

		annotation SummarizationSetBy = Automatic

	column lastFirstName
		dataType: string
		lineageTag: 659a58e4-2f2f-4d6f-bbda-5621e461fb06
		summarizeBy: none
		sourceColumn: lastFirstName

		annotation SummarizationSetBy = Automatic

	column lastInitName
		dataType: string
		lineageTag: c0c65deb-8486-428a-8fb8-d7fe1593833c
		summarizeBy: none
		sourceColumn: lastInitName

		annotation SummarizationSetBy = Automatic

	column initLastName
		dataType: string
		lineageTag: 26c1059f-5b21-41c3-bc89-0d38c575a4c3
		summarizeBy: none
		sourceColumn: initLastName

		annotation SummarizationSetBy = Automatic

	column fullFMLName
		dataType: string
		lineageTag: 2f36032b-02e2-4101-9603-4c134b89c4ef
		summarizeBy: none
		sourceColumn: fullFMLName

		annotation SummarizationSetBy = Automatic

	column fullLFMName
		dataType: string
		lineageTag: f6697481-3883-4a8b-9a43-233ec44ab5e5
		summarizeBy: none
		sourceColumn: fullLFMName

		annotation SummarizationSetBy = Automatic

	column strikeZoneTop
		dataType: string
		lineageTag: a7e7e0c0-6afa-4da0-972b-d6d69aa0b8eb
		summarizeBy: none
		sourceColumn: strikeZoneTop

		annotation SummarizationSetBy = Automatic

	column strikeZoneBottom
		dataType: string
		lineageTag: 05bf1b92-e07b-4caa-852e-1855b03fe355
		summarizeBy: none
		sourceColumn: strikeZoneBottom

		annotation SummarizationSetBy = Automatic

	column 'primaryPosition.code'
		dataType: string
		lineageTag: 01dce22a-f8dc-444f-94c6-0bb874f089e8
		summarizeBy: none
		sourceColumn: primaryPosition.code

		annotation SummarizationSetBy = Automatic

	column 'primaryPosition.name'
		dataType: string
		lineageTag: c490c1d0-b895-4440-937b-504b8c892cdd
		summarizeBy: none
		sourceColumn: primaryPosition.name

		annotation SummarizationSetBy = Automatic

	column 'primaryPosition.type'
		dataType: string
		lineageTag: a279c33a-9aa5-4ac3-bf86-8a7f573325bf
		summarizeBy: none
		sourceColumn: primaryPosition.type

		annotation SummarizationSetBy = Automatic

	column 'primaryPosition.abbreviation'
		dataType: string
		lineageTag: c8b26fe8-6c9b-4841-93aa-a6d0d0be6bb0
		summarizeBy: none
		sourceColumn: primaryPosition.abbreviation

		annotation SummarizationSetBy = Automatic

	column 'batSide.code'
		dataType: string
		lineageTag: 56069efa-4fa5-4226-9185-d5c33aef2fa9
		summarizeBy: none
		sourceColumn: batSide.code

		annotation SummarizationSetBy = Automatic

	column 'batSide.description'
		dataType: string
		lineageTag: 91dee335-a547-41a5-9d13-54d1548406b6
		summarizeBy: none
		sourceColumn: batSide.description

		annotation SummarizationSetBy = Automatic

	column 'pitchHand.code'
		dataType: string
		lineageTag: bf93cab8-f04f-491e-b928-dc88245f57f0
		summarizeBy: none
		sourceColumn: pitchHand.code

		annotation SummarizationSetBy = Automatic

	column 'pitchHand.description'
		dataType: string
		lineageTag: 5b691c32-61dd-4b23-a03f-b36618a81100
		summarizeBy: none
		sourceColumn: pitchHand.description

		annotation SummarizationSetBy = Automatic

	column birthStateProvince
		dataType: string
		lineageTag: 9de77256-adc0-486f-a9b3-87f0bd182b96
		summarizeBy: none
		sourceColumn: birthStateProvince

		annotation SummarizationSetBy = Automatic

	column draftYear
		dataType: string
		lineageTag: a99bae4c-0e05-426d-9e61-be4969c4205d
		summarizeBy: none
		sourceColumn: draftYear

		annotation SummarizationSetBy = Automatic

	column nameMatrilineal
		dataType: string
		lineageTag: c15a0905-15c8-4373-b424-eaaf7dd57252
		summarizeBy: none
		sourceColumn: nameMatrilineal

		annotation SummarizationSetBy = Automatic

	column nameTitle
		dataType: string
		lineageTag: b1b8d267-7aee-42e5-9ff8-cb49b25518b6
		summarizeBy: none
		sourceColumn: nameTitle

		annotation SummarizationSetBy = Automatic

	column nameSuffix
		dataType: string
		lineageTag: 8e2f3fdf-3a55-4c3e-8c71-5a19938e6aef
		summarizeBy: none
		sourceColumn: nameSuffix

		annotation SummarizationSetBy = Automatic

	partition player_info = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\metsy\dev\development\active-projects\mlb-data\data\csv\players\player_info.csv"),[Delimiter=",", Columns=46, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

